### ISSUE TITLE
Disallow units for zero values

### ISSUE THREAD

**Issue by IamEmpty** [Ensighten/spritesmith#61] opened 2016-01-24 14:40 UTC
Please add if statement for background position value, and if value is zero write it without ```px```.
At this moment generated code looks like this:
```stylus
$icon_assistant_x = 0px;
```
But will be excellent, if it would look like this
```stylus
$icon_assistant_x = 0;
```

**Comment by twolfson** [comment] 2016-01-25 00:44
This is a duplicate of https://github.com/Ensighten/grunt-spritesmith/issues/156, https://github.com/Ensighten/grunt-spritesmith/issues/89, https://github.com/twolfson/spritesheet-templates/pull/43, and https://github.com/twolfson/spritesheet-templates/issues/11.

This request is entering CSS optimization territory and encourage developers to use another CSS optimization task after `spritesmith` to handle adjusting rules (e.g. `0px` -> `0`). Here are some tools to evaluate:

- https://www.npmjs.com/package/grunt-csso
    - Wrapper for http://bem.info/tools/csso/
- https://github.com/begriffs/css-ratiocinator

**Closed by twolfson** 2016-01-25 00:44 UTC
